# Generated by Django 4.2.4 on 2023-10-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("producto_servicio", models.CharField(max_length=200)),
                ("descripcion", models.CharField(max_length=200)),
                ("destino", models.EmailField(max_length=200)),
                ("cantidad", models.IntegerField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[("Producto", "Producto"), ("Servicio", "Servicio")],
                        max_length=80,
                    ),
                ),
                ("observaciones", models.CharField(max_length=100)),
                ("solicitado_por", models.CharField(max_length=200)),
                ("aprobado_compra", models.CharField(max_length=200)),
                (
                    "foto_producto",
                    models.ImageField(
                        blank=True, null=True, upload_to="fotos_empleados/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "empleados",
                "ordering": ["-created_at"],
            },
        ),
    ]
